
# load the n-gram frequencies (generated by "build-ngram-frequencies.R")
initialPrediction <- readRDS("../data/start-word-prediction.RData")
freq2ngram <- readRDS("../data/bigram.RData")
freq3ngram <- readRDS("../data/trigram.RData")
freq4ngram <- readRDS("../data/quadgram.RData")

# load bad words file
badWordsFile <- "../data/bad-words.txt"
con <- file(badWordsFile, open = "r")
profanity <- readLines(con, encoding = "UTF-8", skipNul = TRUE)
profanity <- iconv(profanity, "latin1", "ASCII", sub = "")
close(con)

getPredictionWord <- function (userInput, ngrams){
    
    # quadgram (and higher)
    if (ngrams > 3) {
        
        dataTokens <- freq4ngram[freq4ngram$token == userInput,]
        if (nrow(dataTokens) >= 1) {
            return(dataTokens$outcome[1:3])
        }
    }
    
    # trigram
    if (ngrams == 3) {
        
        dataTokens <- freq3ngram[freq3ngram$token == userInput,]
        if (nrow(dataTokens) >= 1) {
            return(dataTokens$outcome[1:3])
        }
    }
    
    # bigram
    if (ngrams < 3) {
        
        dataTokens <- freq2ngram[freq2ngram$token == userInput,]
        if (nrow(dataTokens) >= 1) {
            return(dataTokens$outcome[1:3])
        }
    }
    return(NA) 
}

predictionMatch <- function(userInput, ngrams) {
    userInput <- trimws(userInput, which = c("both"), whitespace = "[ \t\r\n]")
    
    userInput <- tail(userInput, 4)
    print(userInput)
    
    userInput <- paste(userInput, collapse = " ")

    # predict with exactly the text the user entered
    prediction <- getPredictionWord(userInput, ngrams)
    
    print(prediction)
    
    # if no prediction found, try smaller n-grams
    while (is.na(prediction) & ngrams > 1) {
        print('while')
        ngrams <- ngrams - 1
        corpus <- corpus(userInput)
        toks <- tokens(corpus, remove_punct = TRUE)
        grams <- tokens_ngrams(toks, ngrams)
        grams <- str_replace(grams, "_", " ")
        
        for (gram in grams) {
            prediction <- c(prediction[!is.na(prediction)], getPredictionWord(gram, ngrams))
        }
        print(prediction)
    }
    
    if(length(prediction) == 0 | is.na(prediction)){
        return(initialPrediction)
    }
    
    return(prediction)
}


cleanInput <- function(input) {
    
    if (input == "" | is.na(input)) {
        return("")
    }
    
    input <- tolower(input)
    
    # remove URL, email addresses, Twitter handles and hash tags
    input <- gsub("(f|ht)tp(s?)://(.*)[.][a-z]+", "", input, ignore.case = FALSE, perl = TRUE)
    input <- gsub("\\S+[@]\\S+", "", input, ignore.case = FALSE, perl = TRUE)
    input <- gsub("@[^\\s]+", "", input, ignore.case = FALSE, perl = TRUE)
    input <- gsub("#[^\\s]+", "", input, ignore.case = FALSE, perl = TRUE)
    
    # remove ordinal numbers
    input <- gsub("[0-9](?:st|nd|rd|th)", "", input, ignore.case = FALSE, perl = TRUE)
    
    # remove profane words
    input <- removeWords(input, profanity)
    
    # remove punctuation
    input <- gsub("[^\\p{L}'\\s]+", "", input, ignore.case = FALSE, perl = TRUE)
    
    # remove punctuation (leaving ')
    input <- gsub("[.\\-!]", " ", input, ignore.case = FALSE, perl = TRUE)
    
    # trim leading and trailing whitespace
    input <- gsub("^\\s+|\\s+$", "", input)
    input <- stripWhitespace(input)
    
    if (input == "" | is.na(input)) {
        return("")
    }
    
    input <- unlist(strsplit(input, " "))
    
    return(input)
}

predictNextWord <- function(input) {
    
    input <- cleanInput(input)
    
    if (input[1] == "") {
        output <- initialPrediction
    } else if (length(input) > 0) {
        output <- predictionMatch(input, ngrams = length(input) + 1)
    }
    
    output <- sample(unique(output))
    
    return(output)
}

shinyServer(function(input, output) {
    
    # original sentence
    output$userSentence <- renderText({input$userInput});
    
    # reactive controls
    observe({
        words <- predictNextWord(input$userInput)
        output$prediction1 <- reactive({words[1]})
        output$prediction2 <- reactive({words[2]})
        output$prediction3 <- reactive({words[3]})
    })
    
})